base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 3306
  username: root
  password: kenrome001

development:
  <<: *base
  database: ydyb

test:
  <<: *base
  database: ydyb

production:
  <<: *base
  database: ydyb
############################
local: &local
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: kenrome001
  host: 127.0.0.1
  port: 3306
#for exporter
common_development:
  <<: *base
  database: ydyb

local_development:
  <<: *local
  database: forager


##############baidu
baidu:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 3303
  username: root
  password: kenrome001
  database: baidu
